name: HW 2 workflow -> unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install linting and formatting tools
        run: |
          pip install ruff autopep8
      - name: Lint with Ruff
        run: |
          ruff --format=github --target-version=py310 .
        continue-on-error: true
      - name: Run autopep8 (Check formatting)
        run: |
          autopep8 --diff --exit-code --recursive .
        continue-on-error: true
      - name: Lint with Ruff
        run: |
          pip install ruff  
          ruff --format=github --target-version=py310 .
        continue-on-error: true
      - name: Install pytest
        run: |
          pip install pytest coverage
      - name: Test with pytest
        run: |
          coverage run -m pytest  -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
